### ISSUE TITLE
(HEAD) Button variants do not use the box-shadow variable from css

### ISSUE THREAD

**Issue by Arlen22** [Shopify/polaris-react-archive#11377]
## Issue summary

The Button component variants primary and secondary do not use the box-shadow variable from css. 

## Expected behavior

Specifically, `variantPrimary`, `variantSecondary`, `toneSuccess:is(variantPrimary)`, and `toneCritical:is(variantPrimary)` need to have --pc-button-box-shadow normal and active states set to `--p-shadow-button-_variant_-_role_` and `--p-shadow-button-_variant_-_role_-inset` respectively.

https://github.com/Shopify/polaris/blob/f631b229fbb455a1586ea59584085be0f131ea71/polaris-react/src/components/Button/Button.module.scss#L115-L118

## Actual behavior

It's actually just a hard-coded value in Button.module.scss

## Specifications

- Are you using the React components? (Y/N):
- Polaris version number: main HEAD [f631b22](https://github.com/Shopify/polaris/commit/f631b229fbb455a1586ea59584085be0f131ea71)
- Browser: Chrome
- Device: Laptop
- Operating System: Windows 11

**Comment by Arlen22** [comment]
This appears to be related to the excellent code cleanup by @sam-b-rose and @mrcthms. Hopefully they can migrate the updated box shadows over to the theme variables.

**Comment by Arlen22** [comment]
That being said, here's my solution for the time being, which I managed to deduce from the HSL values of the success tone. The need for this is because I changed the brand color and needed an easy way to adjust it that was more or less consistent.

```css

.Polaris-Button--variantPrimary {
  --pc-button-box-shadow:
    0 -0.0625rem 0 0.0625rem var(--p-color-bg-fill-brand-hover) inset,
    0 0 0 0.0625rem var(--p-color-bg-fill-brand-active) inset,
    0 0.03125rem 0 0.09375rem rgba(255, 255, 255, 0.251) inset;
  --pc-button-box-shadow_active:
    -0.0625rem 0 0.0625rem 0 rgba(0, 0, 0, 0.2) inset,
    0.0625rem 0 0.0625rem 0 rgba(0, 0, 0, 0.2) inset,
    0 0.125rem 0 0 rgba(0, 0, 0, 0.6) inset;
}

.Polaris-Button--toneSuccess:is(.Polaris-Button--variantPrimary) {
  --pc-button-box-shadow:
    0 -0.0625rem 0 0.0625rem var(--p-color-bg-fill-success-hover) inset,
    0 0 0 0.0625rem var(--p-color-bg-fill-success-active) inset,
    0 0.03125rem 0 0.09375rem rgba(255, 255, 255, 0.251) inset;
  --pc-button-box-shadow_active:
    -0.0625rem 0 0.0625rem 0 rgba(0, 0, 0, 0.2) inset,
    0.0625rem 0 0.0625rem 0 rgba(0, 0, 0, 0.2) inset,
    0 0.125rem 0 0 rgba(0, 0, 0, 0.6) inset;
}

.Polaris-Button--toneCritical:is(.Polaris-Button--variantPrimary) {
  --pc-button-box-shadow:
    0 -0.0625rem 0 0.0625rem var(--p-color-bg-fill-critical-hover) inset,
    0 0 0 0.0625rem var(--p-color-bg-fill-critical-active) inset,
    0 0.03125rem 0 0.09375rem rgba(255, 255, 255, 0.251) inset;
  --pc-button-box-shadow_active:
    -0.0625rem 0 0.0625rem 0 rgba(0, 0, 0, 0.2) inset,
    0.0625rem 0 0.0625rem 0 rgba(0, 0, 0, 0.2) inset,
    0 0.125rem 0 0 rgba(0, 0, 0, 0.6) inset;
}
```
