### ISSUE TITLE
Production build with CRA 5.0.0 fails due to postcss compilation error

### ISSUE THREAD

**Issue by mbaumbach** [Shopify/polaris-react-archive#4838]
## Issue summary

When using create-react-app 5.0.0 and attempting to perform a production build of the app using the standard build command, the build fails if you include the ESM styles like so:

```javascript
import "@shopify/polaris/build/esm/styles.css";
```

The failure is as follows:

```
Creating an optimized production build...
Failed to compile.

Syntax error: postcss-custom-properties: <css input> Unknown word (1:1)
> 1 | -50% + var(--Polaris-RangeSlider-output-factor)*var(--p-range-slider-thumb-size-base)
    | ^
```

## Expected behavior

A production build successfully runs.

## Actual behavior

An error is thrown from postcss on the following line from the styles.css ESM import:

```css
.Polaris-RangeSlider-SingleThumb__Output { position: absolute; z-index: 20; bottom: var(--p-range-slider-thumb-size-base); left: var(--Polaris-RangeSlider-progress); transform: translateX(calc(-50% + var(--Polaris-RangeSlider-output-factor)*var(--p-range-slider-thumb-size-base))); opacity: 0; visibility: hidden; pointer-events: none; transition-property: opacity, visibility, bottom; transition-duration: 200ms; transition-timing-function: cubic-bezier(0.25, 0.1, 0.25, 1); }
```

Pretty print version:
```css
.Polaris-RangeSlider-SingleThumb__Output {
	position: absolute;
	z-index: 20;
	bottom: var(--p-range-slider-thumb-size-base);
	left: var(--Polaris-RangeSlider-progress);
	transform: translateX(calc(-50% + var(--Polaris-RangeSlider-output-factor)*var(--p-range-slider-thumb-size-base)));
	opacity: 0;
	visibility: hidden;
	pointer-events: none;
	transition-property: opacity, visibility, bottom;
	transition-duration: 200ms;
	transition-timing-function: cubic-bezier(0.25, 0.1, 0.25, 1);
}
```

Looking at the output it looks valid to me, but perhaps I'm missing something. I checked it against a CSS validator and it passed, so this may be a postcss bug.

## Steps to reproduce the problem

1. Install create-react-app 5.0.0
1. Run `create-react-app polaris-test`
2. Add Polaris to the dependencies: `yarn add @shopify/polaris`
3. At the top of the `index.js` file, add the line: `import "@shopify/polaris/build/esm/styles.css";`
4. Run `yarn build`

## Reduced test case

The steps mentioned above work as a reduced test case. I'm not aware of how to provide it with a codesandbox that also performs a production build.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 7.5.0
- Browser: N/A
- Device: MacBook Pro M1
- Operating System: macOS Monterey 12.1
