### ISSUE TITLE
Motion coverage to 90%

### ISSUE THREAD

**Issue by aveline** [Shopify/polaris-react-archive#5339]
**Push motion coverage as high as possible (80-90-100%)**
Document all the remaining divergence on motion and create an approach to consolidate, remove or create new token values. We need to spend more time go deeper into the values we scale but that can be a follow up once we have the values on mainline.

**Comment by lgriffee** [comment]
# Remaining Divergence on Motion (in Polaris-React)

- [x] #5405
- [x] #5427

## Hardcoded duration values

**src/components/TopBar/components/SearchField/SearchField.scss**
| Value | # Instances |
| --- | --- |
| 33ms | 2 |
| 0.01ms | 1 | 

**src/components/TopBar/components/UserMenu/UserMenu.scss**
| Value | # Instances |
| --- | --- |
| 33ms | 1 |

**Approach to consolidate, remove or create new token values**
See comments in #5405

## Replacing `@keyframe` values
**src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss**
```scss
@keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}
```
**src/components/Spinner/Spinner.scss**
```scss
@keyframes loading {
  to {
    transform: rotate(360deg);
  }
}
```
**src/components/ProgressBar/ProgressBar.scss**
```scss
@keyframes fillup {
  0% {
    width: 0;
  }
}
```
**src/components/Navigation/_variables.scss**
```scss
@keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}
```
**src/components/Indicator/Indicator.scss**
```scss
@keyframes bounce {
  from,
  #{map-get($pip-animation, start-scaling-small)},
  #{map-get($pip-animation, finish-scaling)} {
    transform: scale(1);
  }

  #{map-get($pip-animation, finish-scaling-small)} {
    transform: scale(0.85);
  }

  #{map-get($pip-animation, finish-scaling-big)} {
    transform: scale(1.05);
  }
}

@keyframes pulse {
  from,
  #{map-get($pip-animation, finish-scaling-small)} {
    transform: scale(0.85);
    opacity: 1;
  }

  to {
    transform: scale(2.5);
    opacity: 0;
  }
}
```
**src/components/Button/Button.scss**
```scss
@keyframes loading {
  to {
    transform: rotate(360deg);
  }
}
```
**src/components/Backdrop/Backdrop.scss**
```scss
@keyframes fade-in {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}
```
