### ISSUE TITLE
[Polaris for VSCode] Merge autocomplete tokens that will match multiple css properties

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#5469]
sometimes more than one token group will be relevant to the same CSS property. In these cases, we should return all relevant token groups, not just the first match

https://github.com/Shopify/polaris/blob/0692140010a46bc232d0d3013105ff5acd05af8e/polaris-for-vscode/server/src/server.ts#L32-L41

```css
.someCSS {
  box-shadow:  ... /* should return color AND depth tokens*/
  border: ... /* should return color AND shape tokens */
}
```
