### ISSUE TITLE
/snapit requires a changeset entry to run

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#5949]
Either this should be documented and an error message shared or it generates a made up changeset for the snapshot.

**Comment by sam-b-rose** [comment]
@alex-page, #5950 adds documentation regarding needing at least one changeset in order to snapshot release.

Should we also add a file check step like this to the snap.yml workflow? I don't want to over complicate the workflow, but I see how this could be potentially helpful.

```yml
      - name: Check if changesets exist
        uses: andstor/file-existence-action@v1
        with:
          files: '.changeset/*.md'

      - name: Warn if changesets do not exist
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          echo "Missing changsets!"
          echo "Please add a changset for the packages you'd like to snapshot release."
          echo "https://github.com/Shopify/polaris/blob/.github/CONTRIBUTING.md#adding-a-changeset"
          exit 1
```
