### ISSUE TITLE
Create an escape hatch for failures with a context comment

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#7531]

**Comment by dominikwilkowski** [comment]
Just making it explicit and writing it down.
For the Polaris linter we are introducing `errors` to the `warnings` we already have. That’s great because there are some thing we just simply can’t analyze properly with 100% certainty to know if this is a thing on mainline or not. And we want to enable this linter to the CI scripts to the Polaris repo as well as web.

With that we also need to allow individuals to ignore things and this is where my write up comes in.
We should allow consumers to disable individual lines of mainline warnings/errors but ONLY with some addtional text for context so that we can grep the code for `eslint-disable polaris-mainline` (or whatever the rule name will be) and investigate what gaps in our components exist and fix them without blocking.

Example
This will fail currently:
```css
.my_selector {
  display: flex;
}
```
But perhaps this is not off mainline because what this line does is something our layout components can’t do (perhaps is just vertically center aligning a custom component that is complex etc etc)

So you may have to do this:
```css
.my_selector {
  /* eslint-disable polaris-mainline */
  display: flex;
}
```
But this should also fail because it doesn’t give us any context as to why this is not a “mainline fail”
Instead this should b required to ignore lines:
```css
.my_selector {
  /* eslint-disable polaris-mainline context: This line is required because we only use this for vertically aligning this very component which can't be done with the layout components as is... */
  display: flex;
}
```

Now we also need to make sure this is documented well within the error / warning messages all the ay through so consumers always know how to fix things.

The syntax of the above is up for grabs and for now just an illustration of the concept.

**Comment by aaronccasanova** [comment]
Since our coverage tooling is built on [stylelint-polaris](https://github.com/Shopify/polaris/tree/a8d80cfd5630b659a10cf950d07fd91562b63814/stylelint-polaris) we can leverage [stylelint ignore comments](https://stylelint.io/user-guide/ignore-code/#within-files) and enable the [reportDescriptionlessDisables](https://stylelint.io/user-guide/usage/options/#reportdescriptionlessdisables) option to catch disables without context e.g.

```scss
.my_selector {
  /* stylelint-disable-next-line stylelint-polaris -- This line is required because... */
  display: flex;
}
```

That said, I can think of two caveats that might make this more involved:
- We may not want to impose reporting every disable without a description in Web
- There doesn't appear to be an option requiring a rule name is provided with the disable comment e.g.
  `/* stylelint-disable -- This disable does not specify stylelint-polaris */`

If folks consider any of the above caveats a show stopper, we will likely have to write a `stylelint-polaris` rule to lint the disable comments. Open to other suggestions!
