### ISSUE TITLE
npm run build Could not resolve './***.scss.js' from  node_modules/@shopify/polaris/build/esm/components/AppProvider/AppProvider.js error during build

### ISSUE THREAD

**Issue by pmdm-st** [Shopify/polaris-react-archive#9783]
I'm getting an error when I try to build the app using a github action

the error that I'm getting is the following:
npm run build
Could not resolve './***.scss.js' from 
node_modules/@shopify/polaris/build/esm/components/AppProvider/AppProvider.js
error during build

```
Command failed with exit code 1: npm run build
Could not resolve './***.scss.js' from 
node_modules/@shopify/polaris/build/esm/components/AppProvider/AppProvider.js
error during build:
Error: Could not resolve './***.scss.js' from
node_modules/@shopify/polaris/build/esm/components/AppProvider/AppProvider.js
    at error (/home/runner/work/xxxx/xxxx/web/frontend/node_
modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/home/runner/work/box-builder-js/box-builde
r-js/web/frontend/node_modules/rollup/dist/shared/rollup.js:22[46](https://github.com/xxx/xxx/actions/runs/5615794386/job/15216831285#step:5:47)4:24)
    at /home/runner/work/xxx/xxx/web/frontend/node_modules
/rollup/dist/shared/rollup.js:22427:26
```

this is the github yaml file

```
name: Deploy to Firebase Hosting on PR
"on": pull_request
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Create .env file
        run: |
          echo "SECRET_KEY=${{ secrets.ENV_PROD }}" >> .env
      - name: Install npm dependencies
        run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_XXX }}"
          projectId: xxx
```
The ci and build runs without any problems on my local machine, is there any step that I'm missing here?

Could not resolve './***.scss.js' does not exists, it's just a scss file not javascript

Thanks
