### ISSUE TITLE
[DataTable] Add support for "sparse" table density

### ISSUE THREAD

**Issue by bencmilton** [Shopify/polaris-react-archive#9895]
## Feature request summary
The Summer 2023 Polaris Uplift release significantly reduced the row density for `DataTable`s. My understanding is that this is intended to improve usability and readability for typical tables, which are generally relatively long, scrollable and data heavy, which makes it a very sensible _default_ to apply. However, we think there are valid use cases where the old "sparse" styles were preferable and that there should be an easier way to opt back into them.  

## Rationale
The Optimize Team currently supports (and is planning on expanding usage of) many variants of a shared `<MetricCard />` component, which is composed almost entirely of Polaris and Polaris Viz components. Of these variants is a "table" card, which renders formatted Reportify analytics data into a `<DataTable />` component. This table is limited to showing only the first five rows of data and is intended to serve as a preview of the larger dataset, which it links out to.

**After Uplift 2023 (no overrides):**
<img width="950" alt="table-after-uplift" src="https://github.com/Shopify/polaris/assets/9685204/d5a40048-78d4-49ba-8a8e-5b96b74f7be3">

We're temporarily getting around this by applying several hacky CSS overrides, but would _much_ rather find a palatable way to avoid it. 
```css
  /* stylelint-disable-next-line polaris/conventions/selector-disallowed-list -- fix data table bleed spacing */
  [class^='Polaris-DataTable__TableRow'] {
    /* stylelint-disable-next-line selector-max-combinators, selector-max-attribute, polaris/conventions/selector-disallowed-list -- padding-top padding-bottom */
    > [class^='Polaris-DataTable__Cell'] {
      padding-top: var(--p-space-3);
      padding-bottom: var(--p-space-3);

      /* stylelint-disable-next-line selector-max-specificity, selector-max-combinators, selector-max-attribute -- padding-left */
      &:first-child {
        padding-left: var(--p-space-4);
      }

      /* stylelint-disable-next-line selector-max-specificity, selector-max-combinators, selector-max-attribute -- padding-right */
      &:last-child {
        padding-right: var(--p-space-4);
      }
    }
  }
  ``` 

**After adding CSS overrides (rows have additional padding and take up more visual space in the Card component):**
<img width="949" alt="table-after-overrides" src="https://github.com/Shopify/polaris/assets/9685204/35ee1ece-7e60-4deb-b398-fa9068f3ea4e">

My naive first thought would be to deprecate the current `increasedTableDensity` prop in favor of an optional `tableDensity` prop that could handle multiple permutations:
```ts
export type TableDensityType = 'default' | 'dense' | 'sparse';

export interface DataTableProps {
  tableDensity?: TableDensityType;
}
``` 
---

🌟 Feature requests that are not yet planned will be closed. We then use the issue’s :+1: upvotes to track and set priorities. See the [contribution guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md) for more information.
